model:
  image_encoder: vit
  text_encoder: clinicalbert
  fusion: cross_attention

training:
  batch_size: 16
  epochs: 10
  lr: 0.0001

data:
  dataset: MIMIC-CXR
  image_path: /path/to/images
  report_path: /path/to/reports
